#!/usr/bin/bash

sudo pacman -S --needed archiso --noconfirm
sudo pacman -S --needed archlinux-appstream-data --noconfirm
sudo pacman -S --needed aspell --noconfirm
sudo pacman -S --needed aspell-en --noconfirm
sudo pacman -S --needed base --noconfirm
sudo pacman -S --needed base-devel --noconfirm
sudo pacman -S --needed bash-completion --noconfirm
sudo pacman -S --needed cmake --noconfirm
sudo pacman -S --needed make --noconfirm
sudo pacman -S --needed dconf --noconfirm
sudo pacman -S --needed dconf-editor --noconfirm
sudo pacman -S --needed dex --noconfirm
sudo pacman -S --needed dialog --noconfirm
sudo pacman -S --needed devtools --noconfirm
sudo pacman -S --needed dkms --noconfirm
sudo pacman -S --needed dnsutils --noconfirm
sudo pacman -S --needed efitools --noconfirm
sudo pacman -S --needed evince --noconfirm
sudo pacman -S --needed expac --noconfirm
sudo pacman -S --needed eza --noconfirm
sudo pacman -S --needed fwupd --noconfirm
sudo pacman -S --needed git --noconfirm
sudo pacman -S --needed curl --noconfirm
sudo pacman -S --needed htop --noconfirm
sudo pacman -S --needed hardinfo --noconfirm
sudo pacman -S --needed hwdata --noconfirm
sudo pacman -S --needed hwdetect --noconfirm
sudo pacman -S --needed hwinfo --noconfirm
sudo pacman -S --needed intltool --noconfirm
sudo pacman -S --needed libburn --noconfirm
sudo pacman -S --needed libisofs --noconfirm
sudo pacman -S --needed libisoburn --noconfirm
sudo pacman -S --needed linux-headers --noconfirm
sudo pacman -S --needed logrotate --noconfirm
sudo pacman -S --needed lsb-release --noconfirm
sudo pacman -S --needed openssl --noconfirm
sudo pacman -S --needed p7zip --noconfirm
sudo pacman -S --needed packagekit --noconfirm
sudo pacman -S --needed pacman-contrib --noconfirm
sudo pacman -S --needed pacutils --noconfirm
sudo pacman -S --needed pkgfile --noconfirm
sudo pacman -S --needed plocate --noconfirm
sudo pacman -S --needed ripgrep --noconfirm
sudo pacman -S --needed ripgrep-all --noconfirm
sudo pacman -S --needed sdl12-compat --noconfirm
sudo pacman -S --needed sdl2 --noconfirm
sudo pacman -S --needed tldr --noconfirm
sudo pacman -S --needed udftools --noconfirm
sudo pacman -S --needed udisks2 --noconfirm
sudo pacman -S --needed udiskie --noconfirm
sudo pacman -S --needed ark --noconfirm
sudo pacman -S --needed unace --noconfirm
sudo pacman -S --needed unrar --noconfirm
sudo pacman -S --needed unzip --noconfirm
sudo pacman -S --needed upower --noconfirm
sudo pacman -S --needed xdg-utils --noconfirm
sudo pacman -S --needed xdg-desktop-portal-gtk --noconfirm
sudo pacman -S --needed xdg-user-dirs-gtk --noconfirm
sudo pacman -S --needed yad --noconfirm
sudo pacman -S --needed archlinux-wallpaper --noconfirm
sudo pacman -S --needed acpi --noconfirm
sudo pacman -S --needed acpid --noconfirm
sudo pacman -S --needed dosfstools --noconfirm
sudo pacman -S --needed inetutils --noconfirm
sudo pacman -S --needed xapp --noconfirm
sudo pacman -S --needed xdo --noconfirm
sudo pacman -S --needed xdotool --noconfirm
sudo pacman -S --needed zenity --noconfirm
sudo pacman -S --needed inxi --noconfirm
sudo pacman -S --needed os-prober --noconfirm