#!/usr/bin/bash

sudo pacman -S --noconfirm --needed base-devel
sudo pacman -S --noconfirm --needed curl
sudo pacman -S --noconfirm --needed git
sudo pacman -S --noconfirm --needed gksu
sudo pacman -S --noconfirm --needed aic94xx-firmware
sudo pacman -S --noconfirm --needed dialog
sudo pacman -S --noconfirm --needed dnsutils
sudo pacman -S --noconfirm --needed libadwaita-without-adwaita-git
sudo pacman -S --noconfirm --needed linux-headers
sudo pacman -S --noconfirm --needed logrotate
sudo pacman -S --noconfirm --needed ntp
sudo pacman -S --noconfirm --needed upd72020x-fw
sudo pacman -S --noconfirm --needed wd719x-firmware
sudo pacman -S --noconfirm --needed wget
sudo pacman -S --noconfirm --needed xorg-server
sudo pacman -S --noconfirm --needed xorg-apps
sudo pacman -S --noconfirm --needed xorg-xinit
sudo pacman -S --noconfirm --needed xf86-video-vmware
sudo pacman -S --noconfirm --needed mesa
sudo pacman -S --noconfirm --needed xf86-input-libinput
sudo pacman -S --noconfirm --needed xf86-input-elographics
sudo pacman -S --noconfirm --needed nvidia-dkms
sudo pacman -S --noconfirm --needed nvidia-utils
sudo pacman -S --noconfirm --needed nvidia-settings
sudo pacman -S --noconfirm --needed virtualbox-guest-utils
sudo pacman -S --noconfirm --needed os-prober
sudo pacman -S --noconfirm --needed cryptsetup
sudo pacman -S --noconfirm --needed alsa-firmware
sudo pacman -S --noconfirm --needed alsa-plugins
sudo pacman -S --noconfirm --needed alsa-lib
sudo pacman -S --noconfirm --needed alsa-utils
sudo pacman -S --noconfirm --needed gst-libav
sudo pacman -S --noconfirm --needed gst-plugins-bad
sudo pacman -S --noconfirm --needed gst-plugins-base
sudo pacman -S --noconfirm --needed gst-plugins-good
sudo pacman -S --noconfirm --needed gst-plugins-ugly
sudo pacman -S --noconfirm --needed gstreamer
sudo pacman -S --noconfirm --needed libdvdcss
sudo pacman -S --noconfirm --needed pulseaudio
sudo pacman -S --noconfirm --needed pulseaudio-alsa
sudo pacman -S --noconfirm --needed pavucontrol
sudo pacman -S --noconfirm --needed blueberry
sudo pacman -S --noconfirm --needed bluez
sudo pacman -S --noconfirm --needed bluez-libs
sudo pacman -S --noconfirm --needed bluez-utils
sudo pacman -S --noconfirm --needed pulseaudio-bluetooth
sudo pacman -S --noconfirm --needed avahi
sudo pacman -S --noconfirm --needed nss-mdns
sudo pacman -S --noconfirm --needed mobile-broadband-provider-info
sudo pacman -S --noconfirm --needed modemmanager
sudo pacman -S --noconfirm --needed networkmanager
sudo pacman -S --noconfirm --needed network-manager-applet
sudo pacman -S --noconfirm --needed networkmanager-openconnect
sudo pacman -S --noconfirm --needed networkmanager-openvpn
sudo pacman -S --noconfirm --needed networkmanager-pptp
sudo pacman -S --noconfirm --needed networkmanager-vpnc
sudo pacman -S --noconfirm --needed openresolv
sudo pacman -S --noconfirm --needed rtl8821cu-morrownr-dkms-git
sudo pacman -S --noconfirm --needed gvfs
sudo pacman -S --noconfirm --needed gvfs-afc
sudo pacman -S --noconfirm --needed gvfs-gphoto2
sudo pacman -S --noconfirm --needed gvfs-mtp
sudo pacman -S --noconfirm --needed gvfs-nfs
sudo pacman -S --noconfirm --needed gvfs-smb
sudo pacman -S --noconfirm --needed mtpfs
sudo pacman -S --noconfirm --needed udiskie
sudo pacman -S --noconfirm --needed udisks2
sudo pacman -S --noconfirm --needed xdg-user-dirs
sudo pacman -S --noconfirm --needed tumbler
sudo pacman -S --noconfirm --needed ffmpegthumbnailer
sudo pacman -S --noconfirm --needed freetype2
sudo pacman -S --noconfirm --needed libgsf
sudo pacman -S --noconfirm --needed libopenraw
sudo pacman -S --noconfirm --needed poppler-glib
sudo pacman -S --noconfirm --needed poppler-qt5
sudo pacman -S --noconfirm --needed feh
sudo pacman -S --noconfirm --needed firefox
sudo pacman -S --noconfirm --needed imagemagick
sudo pacman -S --noconfirm --needed meld
sudo pacman -S --noconfirm --needed numlockx
sudo pacman -S --noconfirm --needed variety
sudo pacman -S --noconfirm --needed jq
sudo pacman -S --noconfirm --needed pacman-contrib
sudo pacman -S --noconfirm --needed adobe-source-sans-fonts
sudo pacman -S --noconfirm --needed awesome-terminal-fonts
sudo pacman -S --noconfirm --needed noto-fonts
sudo pacman -S --noconfirm --needed ttf-bitstream-vera
sudo pacman -S --noconfirm --needed ttf-dejavu
sudo pacman -S --noconfirm --needed ttf-droid
sudo pacman -S --noconfirm --needed ttf-hack
sudo pacman -S --noconfirm --needed ttf-inconsolata
sudo pacman -S --noconfirm --needed ttf-liberation
sudo pacman -S --noconfirm --needed ttf-roboto
sudo pacman -S --noconfirm --needed ttf-roboto-mono
sudo pacman -S --noconfirm --needed ttf-ubuntu-font-family
sudo pacman -S --noconfirm --needed arc-gtk-theme
sudo pacman -S --noconfirm --needed kvantum
sudo pacman -S --noconfirm --needed arandr
sudo pacman -S --noconfirm --needed bash-completion
sudo pacman -S --noconfirm --needed bat
sudo pacman -S --noconfirm --needed dex
sudo pacman -S --noconfirm --needed edid-decode-git
sudo pacman -S --noconfirm --needed expac
sudo pacman -S --noconfirm --needed file-roller
sudo pacman -S --noconfirm --needed gnome-disk-utility
sudo pacman -S --noconfirm --needed gnome-keyring
sudo pacman -S --noconfirm --needed gparted
sudo pacman -S --noconfirm --needed hardinfo-gtk3
sudo pacman -S --noconfirm --needed htop
sudo pacman -S --noconfirm --needed hddtemp
sudo pacman -S --noconfirm --needed hw-probe
sudo pacman -S --noconfirm --needed intltool
sudo pacman -S --noconfirm --needed iw
sudo pacman -S --noconfirm --needed jsoncpp
sudo pacman -S --noconfirm --needed libmtp
sudo pacman -S --noconfirm --needed laptop-detect
sudo pacman -S --noconfirm --needed lsb-release
sudo pacman -S --noconfirm --needed mlocate
sudo pacman -S --noconfirm --needed oh-my-zsh-git
sudo pacman -S --noconfirm --needed p7zip
sudo pacman -S --noconfirm --needed pkgfile
sudo pacman -S --noconfirm --needed playerctl
sudo pacman -S --noconfirm --needed polkit
sudo pacman -S --noconfirm --needed polkit-gnome
sudo pacman -S --noconfirm --needed qt5ct
sudo pacman -S --noconfirm --needed ripgrep
sudo pacman -S --noconfirm --needed rxvt-unicode
sudo pacman -S --noconfirm --needed tlp
sudo pacman -S --noconfirm --needed unace
sudo pacman -S --noconfirm --needed unrar
sudo pacman -S --noconfirm --needed unzip
sudo pacman -S --noconfirm --needed zenity
sudo pacman -S --noconfirm --needed zsh
sudo pacman -S --noconfirm --needed zsh-completions
sudo pacman -S --noconfirm --needed zsh-syntax-highlighting
sudo pacman -S --noconfirm --needed bibata-cursor-theme-bin
sudo pacman -S --noconfirm --needed ttf-font-awesome
sudo pacman -S --noconfirm --needed ttf-ms-fonts
sudo pacman -S --noconfirm --needed mkinitcpio-openswap
sudo pacman -S --noconfirm --needed alacritty
sudo pacman -S --noconfirm --needed appstream
sudo pacman -S --noconfirm --needed appstream-qt5
sudo pacman -S --noconfirm --needed archiso
sudo pacman -S --noconfirm --needed conky-lua-archers
sudo pacman -S --noconfirm --needed downgrade
sudo pacman -S --noconfirm --needed hardcode-fixer-git
sudo pacman -S --noconfirm --needed inxi
sudo pacman -S --noconfirm --needed neofetch
sudo pacman -S --noconfirm --needed octopi
sudo pacman -S --noconfirm --needed octopi-notifier-qt5
sudo pacman -S --noconfirm --needed paru-bin
sudo pacman -S --noconfirm --needed yay-bin
sudo pacman -S --noconfirm --needed python-pyparted
sudo pacman -S --noconfirm --needed python-pywal
sudo pacman -S --noconfirm --needed rate-mirrors-bin
sudo pacman -S --noconfirm --needed sublime-text-4
sudo pacman -S --noconfirm --needed the_platinum_searcher-bin
sudo pacman -S --noconfirm --needed the_silver_searcher
sudo pacman -S --noconfirm --needed urxvt-fullscreen
sudo pacman -S --noconfirm --needed urxvt-perls
sudo pacman -S --noconfirm --needed urxvt-resize-font-git
sudo pacman -S --noconfirm --needed yad
sudo pacman -S --noconfirm --needed arcolinux-alacritty-git
sudo pacman -S --noconfirm --needed arcolinux-arc-kde
sudo pacman -S --noconfirm --needed arcolinux-bin-git
sudo pacman -S --noconfirm --needed a-candy-beauty-icon-theme-git
sudo pacman -S --noconfirm --needed arcolinux-conky-collection-git
sudo pacman -S --noconfirm --needed arcolinux-desktop-trasher-git
sudo pacman -S --noconfirm --needed arcolinux-fonts-git
sudo pacman -S --noconfirm --needed arcolinux-grub-theme-vimix-git
sudo pacman -S --noconfirm --needed arcolinux-gtk3-arcolinux-candy-beauty-git
sudo pacman -S --noconfirm --needed arcolinux-hblock-git
sudo pacman -S --noconfirm --needed arcolinux-hyprland-profile-git
sudo pacman -S --noconfirm --needed arcolinux-keyring
sudo pacman -S --noconfirm --needed arcolinux-kvantum-git
sudo pacman -S --noconfirm --needed arcolinux-local-applications-git
sudo pacman -S --noconfirm --needed arcolinux-local-applications-all-hide-git
sudo pacman -S --noconfirm --needed arcolinux-local-xfce4-git
sudo pacman -S --noconfirm --needed archlinux-logout-git
sudo pacman -S --noconfirm --needed arcolinux-mirrorlist-git
sudo pacman -S --noconfirm --needed arcolinux-neofetch-git
sudo pacman -S --noconfirm --needed arcolinux-paru-git
sudo pacman -S --noconfirm --needed arcolinux-pipemenus-git
sudo pacman -S --noconfirm --needed arcolinux-qt5-git
sudo pacman -S --noconfirm --needed arcolinux-rofi-git
sudo pacman -S --noconfirm --needed arcolinux-rofi-themes-git
sudo pacman -S --noconfirm --needed arcolinux-root-git
sudo pacman -S --noconfirm --needed arcolinux-system-config-git
sudo pacman -S --noconfirm --needed arcolinux-systemd-services-git
sudo pacman -S --noconfirm --needed archlinux-tweak-tool-git
sudo pacman -S --noconfirm --needed arcolinux-variety-git
sudo pacman -S --noconfirm --needed arcolinux-variety-autostart-git
sudo pacman -S --noconfirm --needed arcolinux-wallpapers-git
sudo pacman -S --noconfirm --needed arcolinux-wayland-profile-git
sudo pacman -S --noconfirm --needed arcolinux-zsh-git
sudo pacman -S --noconfirm --needed arcolinux-hyprland-git
sudo pacman -S --noconfirm --needed arcolinux-xfce-git
sudo pacman -S --noconfirm --needed arcolinux-config-all-desktops-git
sudo pacman -S --noconfirm --needed arcolinux-dconf-all-desktops-git
sudo pacman -S --noconfirm --needed arcolinux-system-installation-git
sudo pacman -S --noconfirm --needed ckbcomp
sudo pacman -S --noconfirm --needed xkeyboard-config
sudo pacman -S --noconfirm --needed upower
sudo pacman -S --noconfirm --needed kcoreaddons5
sudo pacman -S --noconfirm --needed kconfig5
sudo pacman -S --noconfirm --needed ki18n5
sudo pacman -S --noconfirm --needed kservice5
sudo pacman -S --noconfirm --needed kwidgetsaddons5
sudo pacman -S --noconfirm --needed kpmcore
sudo pacman -S --noconfirm --needed boost-libs
sudo pacman -S --noconfirm --needed libpwquality
sudo pacman -S --noconfirm --needed squashfs-tools
sudo pacman -S --noconfirm --needed plasma-framework5
sudo pacman -S --noconfirm --needed hwinfo
sudo pacman -S --noconfirm --needed qt5-xmlpatterns
sudo pacman -S --noconfirm --needed adobe-source-han-sans-jp-fonts
sudo pacman -S --noconfirm --needed adobe-source-han-sans-kr-fonts
sudo pacman -S --noconfirm --needed adobe-source-han-sans-cn-fonts
sudo pacman -S --noconfirm --needed accountsservice
sudo pacman -S --noconfirm --needed sddm
sudo pacman -S --noconfirm --needed arcolinux-sddm-simplicity-git
sudo pacman -S --noconfirm --needed picom
sudo pacman -S --noconfirm --needed lxappearance
sudo pacman -S --noconfirm --needed lxrandr
sudo pacman -S --noconfirm --needed exo
sudo pacman -S --noconfirm --needed thunar
sudo pacman -S --noconfirm --needed thunar-volman
sudo pacman -S --noconfirm --needed tumbler
sudo pacman -S --noconfirm --needed xfce4-appfinder
sudo pacman -S --noconfirm --needed xfce4-terminal
sudo pacman -S --noconfirm --needed thunar-archive-plugin
sudo pacman -S --noconfirm --needed xed
sudo pacman -S --noconfirm --needed arcolinux-foot-git
sudo pacman -S --noconfirm --needed arcolinux-kitty-git
sudo pacman -S --noconfirm --needed arcolinux-wayland-app-hooks-git
sudo pacman -S --noconfirm --needed azote
sudo pacman -S --noconfirm --needed bashtop
sudo pacman -S --noconfirm --needed cava
sudo pacman -S --noconfirm --needed clipman
sudo pacman -S --noconfirm --needed dconf-editor
sudo pacman -S --noconfirm --needed foot
sudo pacman -S --noconfirm --needed grim
sudo pacman -S --noconfirm --needed hyprland-dev
sudo pacman -S --noconfirm --needed hyprpicker-git
sudo pacman -S --noconfirm --needed kitty
sudo pacman -S --noconfirm --needed lf
sudo pacman -S --noconfirm --needed mako
sudo pacman -S --noconfirm --needed micro
sudo pacman -S --noconfirm --needed mpv
sudo pacman -S --noconfirm --needed pamixer
sudo pacman -S --noconfirm --needed rofi-lbonn-wayland-only-git
sudo pacman -S --noconfirm --needed slurp
sudo pacman -S --noconfirm --needed swaybg
sudo pacman -S --noconfirm --needed swayidle
sudo pacman -S --noconfirm --needed swaylock
sudo pacman -S --noconfirm --needed ttf-jetbrains-mono-nerd
sudo pacman -S --noconfirm --needed tty-clock
sudo pacman -S --noconfirm --needed waybar-hyprland-git
sudo pacman -S --noconfirm --needed wf-recorder-git
sudo pacman -S --noconfirm --needed wl-clipboard
sudo pacman -S --noconfirm --needed wlr-randr
sudo pacman -S --noconfirm --needed wofi
sudo pacman -S --noconfirm --needed xdg-desktop-portal-hyprland
sudo pacman -S --noconfirm --needed nomacs-qt6-git
sudo pacman -S --noconfirm --needed nerd-fonts-source-code-pro